// Generated by deno task version
/** The version of the Deno Webview2 module. */
export const Deno_Webview2 = '0.3.1';
/** The version of the Microsoft.Web.WebView2 package. */
export const Microsoft_Web_WebView2 = '1.0.3351.48';
/** The version of the Microsoft.Windows.ImplementationLibrary package. */
export const Microsoft_Windows_ImplementationLibrary = '1.0.250325.1';
