// Generated by deno task convert

/** The event registration token. */
export type EventRegistrationToken = Deno.PointerValue;

/** Loaded webview2 funcs. */
export type Webview2Funcs = Deno.DynamicLibrary<WEBVIEW2_FUNCS>;

/** The result type for WebView2 functions. */
export type WEBVIEW2_FUNCS = {
  readonly GetDllVersion: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly CreateWebView2: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly InitWebView2: {
    readonly parameters: ['pointer'];
    readonly result: 'pointer';
  };
  readonly CreateEnvironments: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly CreateSettings: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly InitSettings: {
    readonly parameters: ['pointer'];
    readonly result: 'pointer';
  };
  readonly CreateControllers: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly InitControllers: {
    readonly parameters: ['pointer'];
    readonly result: 'pointer';
  };
  readonly CreateEventRegistrationToken: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly RemoveEventRegistrationToken: {
    readonly parameters: ['pointer'];
    readonly result: 'void';
  };
  readonly CreateJStream: {
    readonly parameters: [
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
    ];
    readonly result: 'pointer';
  };
  readonly CreateCoreWebView2Environment: {
    readonly parameters: ['pointer', 'function'];
    readonly result: 'i32';
  };
  readonly CreateCoreWebView2EnvironmentWithOptions: {
    readonly parameters: [
      'pointer',
      'pointer',
      'pointer',
      'pointer',
      'function',
    ];
    readonly result: 'i32';
  };
  readonly CompareBrowserVersions: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly GetAvailableCoreWebView2BrowserVersionString: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly GetAvailableCoreWebView2BrowserVersionStringWithOptions: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly CreateCoreWebView2Controller: {
    readonly parameters: ['pointer', 'pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly CreateWebResourceResponse: {
    readonly parameters: [
      'pointer',
      'pointer',
      'i32',
      'pointer',
      'pointer',
      'pointer',
    ];
    readonly result: 'i32';
  };
  readonly get_IsScriptEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsScriptEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_IsWebMessageEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsWebMessageEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_AreDefaultScriptDialogsEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_AreDefaultScriptDialogsEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_IsStatusBarEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsStatusBarEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_AreDevToolsEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_AreDevToolsEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_AreDefaultContextMenusEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_AreDefaultContextMenusEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_AreHostObjectsAllowed: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_AreHostObjectsAllowed: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_IsZoomControlEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsZoomControlEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_IsBuiltInErrorPageEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsBuiltInErrorPageEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_UserAgent: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_UserAgent: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_AreBrowserAcceleratorKeysEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_AreBrowserAcceleratorKeysEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_IsPasswordAutosaveEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsPasswordAutosaveEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_IsGeneralAutofillEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsGeneralAutofillEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_IsPinchZoomEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsPinchZoomEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_IsSwipeNavigationEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsSwipeNavigationEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_HiddenPdfToolbarItems: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_HiddenPdfToolbarItems: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_IsReputationCheckingRequired: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsReputationCheckingRequired: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_IsNonClientRegionSupportEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsNonClientRegionSupportEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly add_AcceleratorKeyPressed: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_AcceleratorKeyPressed: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_Bounds: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_Bounds: {
    readonly parameters: ['pointer', 'buffer'];
    readonly result: 'i32';
  };
  readonly Close: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly get_CoreWebView2: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_GotFocus: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_GotFocus: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_IsVisible: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_IsVisible: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly add_LostFocus: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_LostFocus: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly MoveFocus: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly add_MoveFocusRequested: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_MoveFocusRequested: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NotifyParentWindowPositionChanged: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly get_ParentWindow: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_ParentWindow: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly SetBoundsAndZoomFactor: {
    readonly parameters: ['pointer', 'buffer', 'f64'];
    readonly result: 'i32';
  };
  readonly get_ZoomFactor: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_ZoomFactor: {
    readonly parameters: ['pointer', 'f64'];
    readonly result: 'i32';
  };
  readonly add_ZoomFactorChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_ZoomFactorChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_DefaultBackgroundColor: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_DefaultBackgroundColor: {
    readonly parameters: ['pointer', 'buffer'];
    readonly result: 'i32';
  };
  readonly add_RasterizationScaleChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_RasterizationScaleChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_BoundsMode: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_BoundsMode: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_RasterizationScale: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_RasterizationScale: {
    readonly parameters: ['pointer', 'f64'];
    readonly result: 'i32';
  };
  readonly get_ShouldDetectMonitorScaleChanges: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_ShouldDetectMonitorScaleChanges: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly get_AllowExternalDrop: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly put_AllowExternalDrop: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly CallDevToolsProtocolMethod: {
    readonly parameters: ['pointer', 'pointer', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly GetDevToolsProtocolEventReceiver: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly OpenDevToolsWindow: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly add_DocumentTitleChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_DocumentTitleChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_DocumentTitle: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_HistoryChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_HistoryChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly PostWebMessageAsJson: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly PostWebMessageAsString: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_WebMessageReceived: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_WebMessageReceived: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Navigate: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_NavigationCompleted: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_NavigationCompleted: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_NavigationStarting: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_NavigationStarting: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NavigateToString: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_FrameNavigationCompleted: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_FrameNavigationCompleted: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_FrameNavigationStarting: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_FrameNavigationStarting: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_PermissionRequested: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_PermissionRequested: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_ScriptDialogOpening: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_ScriptDialogOpening: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly AddScriptToExecuteOnDocumentCreated: {
    readonly parameters: ['pointer', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly RemoveScriptToExecuteOnDocumentCreated: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly ExecuteScript: {
    readonly parameters: ['pointer', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly AddHostObjectToScript: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly RemoveHostObjectFromScript: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_Source: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_SourceChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_SourceChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Reload: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly get_CanGoBack: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_CanGoForward: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly GoBack: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly GoForward: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly Stop: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly add_ContentLoading: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_ContentLoading: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_ProcessFailed: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_ProcessFailed: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_Settings: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly CapturePreview: {
    readonly parameters: ['pointer', 'i32', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly get_BrowserProcessId: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_NewWindowRequested: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_NewWindowRequested: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_ContainsFullScreenElementChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_ContainsFullScreenElementChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_ContainsFullScreenElement: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_WebResourceRequested: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_WebResourceRequested: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly AddWebResourceRequestedFilter: {
    readonly parameters: ['pointer', 'pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly RemoveWebResourceRequestedFilter: {
    readonly parameters: ['pointer', 'pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly add_WindowCloseRequested: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_WindowCloseRequested: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_DOMContentLoaded: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly add_WebResourceResponseReceived: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_CookieManager: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_Environment: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NavigateWithWebResourceRequest: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_DOMContentLoaded: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly remove_WebResourceResponseReceived: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly SetVirtualHostNameToFolderMapping: {
    readonly parameters: ['pointer', 'pointer', 'pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly ClearVirtualHostNameToFolderMapping: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly get_IsSuspended: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly TrySuspend: {
    readonly parameters: ['pointer', 'function'];
    readonly result: 'i32';
  };
  readonly Resume: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly WebMessageReceivedEventArgs_get_Source: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebMessageReceivedEventArgs_get_WebMessageAsJson: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebMessageReceivedEventArgs_TryGetWebMessageAsString: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly IStream_Read: {
    readonly parameters: ['pointer', 'pointer', 'u32', 'pointer'];
    readonly result: 'i32';
  };
  readonly IStream_Write: {
    readonly parameters: ['pointer', 'pointer', 'u32', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_Contains: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_GetHeader: {
    readonly parameters: ['pointer', 'pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_GetHeaders: {
    readonly parameters: ['pointer', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_GetIterator: {
    readonly parameters: ['pointer', 'function'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_RemoveHeader: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_SetHeader: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_get_Content: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_get_Headers: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_get_Method: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_get_Uri: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_put_Content: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_put_Method: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_put_Uri: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_get_Content: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_get_Headers: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_get_ReasonPhrase: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_get_StatusCode: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_put_Content: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_put_ReasonPhrase: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_put_StatusCode: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly WebResourceRequestedEventArgs_get_Request: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequestedEventArgs_get_ResourceContext: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequestedEventArgs_get_Response: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequestedEventArgs_GetDeferral: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequestedEventArgs_put_Response: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
};
