// Generated by deno task convert

import type { WEBVIEW2_FUNCS } from './webview2_types.ts';

/** The parameters for the WebView2 functions. */
export const params: WEBVIEW2_FUNCS = {
  Global_GetDllVersion: {
    parameters: [],
    result: 'pointer',
  },
  COM_AddRef: {
    parameters: ['pointer'],
    result: 'u32',
  },
  COM_Release: {
    parameters: ['pointer'],
    result: 'u32',
  },
  WebView2_Destroy: {
    parameters: ['pointer'],
    result: 'void',
  },
  Environments_Destroy: {
    parameters: ['pointer'],
    result: 'void',
  },
  Settings_Destroy: {
    parameters: ['pointer'],
    result: 'void',
  },
  Controllers_Destroy: {
    parameters: ['pointer'],
    result: 'void',
  },
  WebView2_Create: {
    parameters: [],
    result: 'pointer',
  },
  WebView2_Init: {
    parameters: ['pointer'],
    result: 'pointer',
  },
  Environments_Create: {
    parameters: [],
    result: 'pointer',
  },
  Settings_Create: {
    parameters: [],
    result: 'pointer',
  },
  Settings_Init: {
    parameters: ['pointer'],
    result: 'pointer',
  },
  Controllers_Create: {
    parameters: [],
    result: 'pointer',
  },
  Controllers_Init: {
    parameters: ['pointer'],
    result: 'pointer',
  },
  EventRegistrationToken_Create: {
    parameters: [],
    result: 'pointer',
  },
  EventRegistrationToken_Remove: {
    parameters: ['pointer'],
    result: 'void',
  },
  JStream_Create: {
    parameters: [
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
    ],
    result: 'pointer',
  },
  Global_CreateCoreWebView2Environment: {
    parameters: ['pointer', 'function'],
    result: 'i32',
  },
  Global_CreateCoreWebView2EnvironmentWithOptions: {
    parameters: ['pointer', 'pointer', 'pointer', 'pointer', 'function'],
    result: 'i32',
  },
  Global_CompareBrowserVersions: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  Global_GetAvailableCoreWebView2BrowserVersionString: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Global_GetAvailableCoreWebView2BrowserVersionStringWithOptions: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  Environments_CreateCoreWebView2Controller: {
    parameters: ['pointer', 'pointer', 'function', 'pointer'],
    result: 'i32',
  },
  Environments_CreateWebResourceResponse: {
    parameters: ['pointer', 'pointer', 'i32', 'pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  Settings_get_IsScriptEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsScriptEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_IsWebMessageEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsWebMessageEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_AreDefaultScriptDialogsEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_AreDefaultScriptDialogsEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_IsStatusBarEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsStatusBarEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_AreDevToolsEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_AreDevToolsEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_AreDefaultContextMenusEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_AreDefaultContextMenusEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_AreHostObjectsAllowed: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_AreHostObjectsAllowed: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_IsZoomControlEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsZoomControlEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_IsBuiltInErrorPageEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsBuiltInErrorPageEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_UserAgent: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_UserAgent: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_get_AreBrowserAcceleratorKeysEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_AreBrowserAcceleratorKeysEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_IsPasswordAutosaveEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsPasswordAutosaveEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_IsGeneralAutofillEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsGeneralAutofillEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_IsPinchZoomEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsPinchZoomEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_IsSwipeNavigationEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsSwipeNavigationEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_HiddenPdfToolbarItems: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_HiddenPdfToolbarItems: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_get_IsReputationCheckingRequired: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsReputationCheckingRequired: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Settings_get_IsNonClientRegionSupportEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Settings_put_IsNonClientRegionSupportEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Controllers_add_AcceleratorKeyPressed: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  Controllers_remove_AcceleratorKeyPressed: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_get_Bounds: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_put_Bounds: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  Controllers_Close: {
    parameters: ['pointer'],
    result: 'i32',
  },
  Controllers_get_CoreWebView2: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_add_GotFocus: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  Controllers_remove_GotFocus: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_get_IsVisible: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_put_IsVisible: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Controllers_add_LostFocus: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  Controllers_remove_LostFocus: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_MoveFocus: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Controllers_add_MoveFocusRequested: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  Controllers_remove_MoveFocusRequested: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_NotifyParentWindowPositionChanged: {
    parameters: ['pointer'],
    result: 'i32',
  },
  Controllers_get_ParentWindow: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_put_ParentWindow: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_SetBoundsAndZoomFactor: {
    parameters: ['pointer', 'buffer', 'f64'],
    result: 'i32',
  },
  Controllers_get_ZoomFactor: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_put_ZoomFactor: {
    parameters: ['pointer', 'f64'],
    result: 'i32',
  },
  Controllers_add_ZoomFactorChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  Controllers_remove_ZoomFactorChanged: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_get_DefaultBackgroundColor: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_put_DefaultBackgroundColor: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  Controllers_add_RasterizationScaleChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  Controllers_remove_RasterizationScaleChanged: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_get_BoundsMode: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_put_BoundsMode: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Controllers_get_RasterizationScale: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_put_RasterizationScale: {
    parameters: ['pointer', 'f64'],
    result: 'i32',
  },
  Controllers_get_ShouldDetectMonitorScaleChanges: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_put_ShouldDetectMonitorScaleChanges: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Controllers_get_AllowExternalDrop: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  Controllers_put_AllowExternalDrop: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  Deferral_Complete: {
    parameters: ['pointer'],
    result: 'i32',
  },
  WebView2_CallDevToolsProtocolMethod: {
    parameters: ['pointer', 'pointer', 'pointer', 'function'],
    result: 'i32',
  },
  WebView2_GetDevToolsProtocolEventReceiver: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_OpenDevToolsWindow: {
    parameters: ['pointer'],
    result: 'i32',
  },
  WebView2_add_DocumentTitleChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_DocumentTitleChanged: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_get_DocumentTitle: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_HistoryChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_HistoryChanged: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_PostWebMessageAsJson: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_PostWebMessageAsString: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_WebMessageReceived: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_WebMessageReceived: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_Navigate: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_NavigationCompleted: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_NavigationCompleted: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_NavigationStarting: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_NavigationStarting: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_NavigateToString: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_FrameNavigationCompleted: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_FrameNavigationCompleted: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_FrameNavigationStarting: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_FrameNavigationStarting: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_PermissionRequested: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_PermissionRequested: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_ScriptDialogOpening: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_ScriptDialogOpening: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_AddScriptToExecuteOnDocumentCreated: {
    parameters: ['pointer', 'pointer', 'function'],
    result: 'i32',
  },
  WebView2_RemoveScriptToExecuteOnDocumentCreated: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_ExecuteScript: {
    parameters: ['pointer', 'pointer', 'function'],
    result: 'i32',
  },
  WebView2_AddHostObjectToScript: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_RemoveHostObjectFromScript: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_get_Source: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_SourceChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_SourceChanged: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_Reload: {
    parameters: ['pointer'],
    result: 'i32',
  },
  WebView2_get_CanGoBack: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_get_CanGoForward: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_GoBack: {
    parameters: ['pointer'],
    result: 'i32',
  },
  WebView2_GoForward: {
    parameters: ['pointer'],
    result: 'i32',
  },
  WebView2_Stop: {
    parameters: ['pointer'],
    result: 'i32',
  },
  WebView2_add_ContentLoading: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_ContentLoading: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_ProcessFailed: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_ProcessFailed: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_get_Settings: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_CapturePreview: {
    parameters: ['pointer', 'i32', 'pointer', 'function'],
    result: 'i32',
  },
  WebView2_get_BrowserProcessId: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_NewWindowRequested: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_NewWindowRequested: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_ContainsFullScreenElementChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_ContainsFullScreenElementChanged: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_get_ContainsFullScreenElement: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_WebResourceRequested: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_WebResourceRequested: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_AddWebResourceRequestedFilter: {
    parameters: ['pointer', 'pointer', 'i32'],
    result: 'i32',
  },
  WebView2_RemoveWebResourceRequestedFilter: {
    parameters: ['pointer', 'pointer', 'i32'],
    result: 'i32',
  },
  WebView2_add_WindowCloseRequested: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_WindowCloseRequested: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_add_DOMContentLoaded: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_add_WebResourceResponseReceived: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  WebView2_get_CookieManager: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_get_Environment: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_NavigateWithWebResourceRequest: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_DOMContentLoaded: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_remove_WebResourceResponseReceived: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_SetVirtualHostNameToFolderMapping: {
    parameters: ['pointer', 'pointer', 'pointer', 'i32'],
    result: 'i32',
  },
  WebView2_ClearVirtualHostNameToFolderMapping: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_get_IsSuspended: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebView2_TrySuspend: {
    parameters: ['pointer', 'function'],
    result: 'i32',
  },
  WebView2_Resume: {
    parameters: ['pointer'],
    result: 'i32',
  },
  WebMessageReceivedEventArgs_get_Source: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  WebMessageReceivedEventArgs_get_WebMessageAsJson: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  WebMessageReceivedEventArgs_TryGetWebMessageAsString: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  IStream_Read: {
    parameters: ['pointer', 'pointer', 'u32', 'pointer'],
    result: 'i32',
  },
  IStream_Write: {
    parameters: ['pointer', 'pointer', 'u32', 'pointer'],
    result: 'i32',
  },
  HttpRequestHeaders_Contains: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  HttpRequestHeaders_GetHeader: {
    parameters: ['pointer', 'pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  HttpRequestHeaders_GetHeaders: {
    parameters: ['pointer', 'pointer', 'function'],
    result: 'i32',
  },
  HttpRequestHeaders_GetIterator: {
    parameters: ['pointer', 'function'],
    result: 'i32',
  },
  HttpRequestHeaders_RemoveHeader: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  HttpRequestHeaders_SetHeader: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequest_get_Content: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequest_get_Headers: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequest_get_Method: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequest_get_Uri: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequest_put_Content: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequest_put_Method: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequest_put_Uri: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceResponse_get_Content: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceResponse_get_Headers: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceResponse_get_ReasonPhrase: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceResponse_get_StatusCode: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceResponse_put_Content: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceResponse_put_ReasonPhrase: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceResponse_put_StatusCode: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  WebResourceRequestedEventArgs_get_Request: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequestedEventArgs_get_ResourceContext: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequestedEventArgs_get_Response: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequestedEventArgs_GetDeferral: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  WebResourceRequestedEventArgs_put_Response: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  HttpResponseHeaders_Contains: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  HttpResponseHeaders_GetHeader: {
    parameters: ['pointer', 'pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  HttpResponseHeaders_GetHeaders: {
    parameters: ['pointer', 'pointer', 'function'],
    result: 'i32',
  },
  HttpResponseHeaders_GetIterator: {
    parameters: ['pointer', 'function'],
    result: 'i32',
  },
  HttpResponseHeaders_AppendHeader: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
};
