// Generated by deno task convert

/** The event registration token. */
export type EventRegistrationToken = Deno.PointerValue;

/** Loaded webview2 funcs. */
export type Webview2Funcs = Deno.DynamicLibrary<WEBVIEW2_FUNCS>;

/** The result type for WebView2 functions. */
export type WEBVIEW2_FUNCS = {
  readonly Global_GetDllVersion: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly COM_AddRef: {
    readonly parameters: ['pointer'];
    readonly result: 'u32';
  };
  readonly COM_Release: {
    readonly parameters: ['pointer'];
    readonly result: 'u32';
  };
  readonly WebView2_Destroy: {
    readonly parameters: ['pointer'];
    readonly result: 'void';
  };
  readonly Environments_Destroy: {
    readonly parameters: ['pointer'];
    readonly result: 'void';
  };
  readonly Settings_Destroy: {
    readonly parameters: ['pointer'];
    readonly result: 'void';
  };
  readonly Controllers_Destroy: {
    readonly parameters: ['pointer'];
    readonly result: 'void';
  };
  readonly WebView2_Create: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly WebView2_Init: {
    readonly parameters: ['pointer'];
    readonly result: 'pointer';
  };
  readonly Environments_Create: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly Settings_Create: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly Settings_Init: {
    readonly parameters: ['pointer'];
    readonly result: 'pointer';
  };
  readonly Controllers_Create: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly Controllers_Init: {
    readonly parameters: ['pointer'];
    readonly result: 'pointer';
  };
  readonly EventRegistrationToken_Create: {
    readonly parameters: [];
    readonly result: 'pointer';
  };
  readonly EventRegistrationToken_Remove: {
    readonly parameters: ['pointer'];
    readonly result: 'void';
  };
  readonly JStream_Create: {
    readonly parameters: [
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
      'function',
    ];
    readonly result: 'pointer';
  };
  readonly Global_CreateCoreWebView2Environment: {
    readonly parameters: ['pointer', 'function'];
    readonly result: 'i32';
  };
  readonly Global_CreateCoreWebView2EnvironmentWithOptions: {
    readonly parameters: [
      'pointer',
      'pointer',
      'pointer',
      'pointer',
      'function',
    ];
    readonly result: 'i32';
  };
  readonly Global_CompareBrowserVersions: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Global_GetAvailableCoreWebView2BrowserVersionString: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Global_GetAvailableCoreWebView2BrowserVersionStringWithOptions: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Environments_CreateCoreWebView2Controller: {
    readonly parameters: ['pointer', 'pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly Environments_CreateWebResourceResponse: {
    readonly parameters: [
      'pointer',
      'pointer',
      'i32',
      'pointer',
      'pointer',
      'pointer',
    ];
    readonly result: 'i32';
  };
  readonly Settings_get_IsScriptEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsScriptEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_IsWebMessageEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsWebMessageEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_AreDefaultScriptDialogsEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_AreDefaultScriptDialogsEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_IsStatusBarEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsStatusBarEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_AreDevToolsEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_AreDevToolsEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_AreDefaultContextMenusEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_AreDefaultContextMenusEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_AreHostObjectsAllowed: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_AreHostObjectsAllowed: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_IsZoomControlEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsZoomControlEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_IsBuiltInErrorPageEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsBuiltInErrorPageEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_UserAgent: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_UserAgent: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_get_AreBrowserAcceleratorKeysEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_AreBrowserAcceleratorKeysEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_IsPasswordAutosaveEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsPasswordAutosaveEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_IsGeneralAutofillEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsGeneralAutofillEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_IsPinchZoomEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsPinchZoomEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_IsSwipeNavigationEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsSwipeNavigationEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_HiddenPdfToolbarItems: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_HiddenPdfToolbarItems: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_get_IsReputationCheckingRequired: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsReputationCheckingRequired: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Settings_get_IsNonClientRegionSupportEnabled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Settings_put_IsNonClientRegionSupportEnabled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Controllers_add_AcceleratorKeyPressed: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_remove_AcceleratorKeyPressed: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_get_Bounds: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_put_Bounds: {
    readonly parameters: ['pointer', 'buffer'];
    readonly result: 'i32';
  };
  readonly Controllers_Close: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_get_CoreWebView2: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_add_GotFocus: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_remove_GotFocus: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_get_IsVisible: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_put_IsVisible: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Controllers_add_LostFocus: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_remove_LostFocus: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_MoveFocus: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Controllers_add_MoveFocusRequested: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_remove_MoveFocusRequested: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_NotifyParentWindowPositionChanged: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_get_ParentWindow: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_put_ParentWindow: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_SetBoundsAndZoomFactor: {
    readonly parameters: ['pointer', 'buffer', 'f64'];
    readonly result: 'i32';
  };
  readonly Controllers_get_ZoomFactor: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_put_ZoomFactor: {
    readonly parameters: ['pointer', 'f64'];
    readonly result: 'i32';
  };
  readonly Controllers_add_ZoomFactorChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_remove_ZoomFactorChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_get_DefaultBackgroundColor: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_put_DefaultBackgroundColor: {
    readonly parameters: ['pointer', 'u32'];
    readonly result: 'i32';
  };
  readonly Controllers_add_RasterizationScaleChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_remove_RasterizationScaleChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_get_BoundsMode: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_put_BoundsMode: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Controllers_get_RasterizationScale: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_put_RasterizationScale: {
    readonly parameters: ['pointer', 'f64'];
    readonly result: 'i32';
  };
  readonly Controllers_get_ShouldDetectMonitorScaleChanges: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_put_ShouldDetectMonitorScaleChanges: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Controllers_get_AllowExternalDrop: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly Controllers_put_AllowExternalDrop: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly Deferral_Complete: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_CallDevToolsProtocolMethod: {
    readonly parameters: ['pointer', 'pointer', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly WebView2_GetDevToolsProtocolEventReceiver: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_OpenDevToolsWindow: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_DocumentTitleChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_DocumentTitleChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_get_DocumentTitle: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_HistoryChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_HistoryChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_PostWebMessageAsJson: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_PostWebMessageAsString: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_WebMessageReceived: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_WebMessageReceived: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_Navigate: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_NavigationCompleted: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_NavigationCompleted: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_NavigationStarting: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_NavigationStarting: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_NavigateToString: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_FrameNavigationCompleted: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_FrameNavigationCompleted: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_FrameNavigationStarting: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_FrameNavigationStarting: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_PermissionRequested: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_PermissionRequested: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_ScriptDialogOpening: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_ScriptDialogOpening: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_AddScriptToExecuteOnDocumentCreated: {
    readonly parameters: ['pointer', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly WebView2_RemoveScriptToExecuteOnDocumentCreated: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_ExecuteScript: {
    readonly parameters: ['pointer', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly WebView2_AddHostObjectToScript: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_RemoveHostObjectFromScript: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_get_Source: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_SourceChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_SourceChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_Reload: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_get_CanGoBack: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_get_CanGoForward: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_GoBack: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_GoForward: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_Stop: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_ContentLoading: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_ContentLoading: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_ProcessFailed: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_ProcessFailed: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_get_Settings: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_CapturePreview: {
    readonly parameters: ['pointer', 'i32', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly WebView2_get_BrowserProcessId: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_NewWindowRequested: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_NewWindowRequested: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_ContainsFullScreenElementChanged: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_ContainsFullScreenElementChanged: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_get_ContainsFullScreenElement: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_WebResourceRequested: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_WebResourceRequested: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_AddWebResourceRequestedFilter: {
    readonly parameters: ['pointer', 'pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly WebView2_RemoveWebResourceRequestedFilter: {
    readonly parameters: ['pointer', 'pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly WebView2_add_WindowCloseRequested: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_WindowCloseRequested: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_DOMContentLoaded: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_add_WebResourceResponseReceived: {
    readonly parameters: ['pointer', 'function', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_get_CookieManager: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_get_Environment: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_NavigateWithWebResourceRequest: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_DOMContentLoaded: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_remove_WebResourceResponseReceived: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_SetVirtualHostNameToFolderMapping: {
    readonly parameters: ['pointer', 'pointer', 'pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly WebView2_ClearVirtualHostNameToFolderMapping: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_get_IsSuspended: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebView2_TrySuspend: {
    readonly parameters: ['pointer', 'function'];
    readonly result: 'i32';
  };
  readonly WebView2_Resume: {
    readonly parameters: ['pointer'];
    readonly result: 'i32';
  };
  readonly WebMessageReceivedEventArgs_get_Source: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebMessageReceivedEventArgs_get_WebMessageAsJson: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebMessageReceivedEventArgs_TryGetWebMessageAsString: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly IStream_Read: {
    readonly parameters: ['pointer', 'pointer', 'u32', 'pointer'];
    readonly result: 'i32';
  };
  readonly IStream_Write: {
    readonly parameters: ['pointer', 'pointer', 'u32', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_Contains: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_GetHeader: {
    readonly parameters: ['pointer', 'pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_GetHeaders: {
    readonly parameters: ['pointer', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_GetIterator: {
    readonly parameters: ['pointer', 'function'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_RemoveHeader: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpRequestHeaders_SetHeader: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_get_Content: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_get_Headers: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_get_Method: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_get_Uri: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_put_Content: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_put_Method: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequest_put_Uri: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_get_Content: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_get_Headers: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_get_ReasonPhrase: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_get_StatusCode: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_put_Content: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_put_ReasonPhrase: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceResponse_put_StatusCode: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly WebResourceRequestedEventArgs_get_Request: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequestedEventArgs_get_ResourceContext: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequestedEventArgs_get_Response: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequestedEventArgs_GetDeferral: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly WebResourceRequestedEventArgs_put_Response: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpResponseHeaders_Contains: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpResponseHeaders_GetHeader: {
    readonly parameters: ['pointer', 'pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpResponseHeaders_GetHeaders: {
    readonly parameters: ['pointer', 'pointer', 'function'];
    readonly result: 'i32';
  };
  readonly HttpResponseHeaders_GetIterator: {
    readonly parameters: ['pointer', 'function'];
    readonly result: 'i32';
  };
  readonly NavigationStartingEventArgs_get_Uri: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NavigationStartingEventArgs_get_IsUserInitiated: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NavigationStartingEventArgs_get_IsRedirected: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NavigationStartingEventArgs_get_Cancel: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NavigationStartingEventArgs_put_Cancel: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly NavigationStartingEventArgs_get_NavigationId: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NavigationCompletedEventArgs_get_IsSuccess: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NavigationCompletedEventArgs_get_WebErrorStatus: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NavigationCompletedEventArgs_get_NavigationId: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NewWindowRequestedEventArgs_get_Uri: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NewWindowRequestedEventArgs_get_IsUserInitiated: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NewWindowRequestedEventArgs_get_Handled: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly NewWindowRequestedEventArgs_put_Handled: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly NewWindowRequestedEventArgs_GetDeferral: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly PermissionRequestedEventArgs_get_Uri: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly PermissionRequestedEventArgs_get_PermissionKind: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly PermissionRequestedEventArgs_get_IsUserInitiated: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly PermissionRequestedEventArgs_get_State: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly PermissionRequestedEventArgs_put_State: {
    readonly parameters: ['pointer', 'i32'];
    readonly result: 'i32';
  };
  readonly PermissionRequestedEventArgs_GetDeferral: {
    readonly parameters: ['pointer', 'pointer'];
    readonly result: 'i32';
  };
  readonly HttpResponseHeaders_AppendHeader: {
    readonly parameters: ['pointer', 'pointer', 'pointer'];
    readonly result: 'i32';
  };
};
